src/activate.rs
I wrapped every call to `deactivate()` I could find, except one in `activation_confirmation()` that I'm not sure should be prevented.
=> Check auto-rollback flag before deactivating

flake.lock, flake.nix
I've been meaning to try deploy-rs, but I run macOS; since it doesn't currently build there (the `activate` binary has a linux-only inotify dependency, and there was a version incompatibility that prevented building on my OS release), here's a patch that makes it work.
I think this PR ought to retain compatibility with Linux.
* Bumps nixpkgs to a version that ships rust 1.47, as older binaries don't correctly link on macOS 11.0
* Special-cases out the `activate` binary on macOS (and activates `singleStep` mode there for https://github.com/nmattia/naersk/issues/127
* Adds some native build flags necessary to get a working build env on macOS.
Hope this looks reasonable! I'm still evaluating deploy-rs, but it does show `--help` on macOS with this change, at least (:
=> Fix running & building under macOS (Big Sur)

flake.nix, src/utils/deploy.rs, src/utils/mod.rs, src/utils/push.rs
This addresses #13.
This PR rips out the `current_exe` field, preferring to write an `activate-rs` script that points to the platform-appropriate activation binary.
Then, the deploy binary attempts to use that activate-rs script to activate the profile closure.
I've successfully run a deploy to an amd64 linux installation from my intel macOS machine, so I suspect this might work (:
=> Use the stored activate binary appropriate for target platform

Cargo.lock, Cargo.toml
This addresses #27: Rust 1.45.2 is what ships in the 20.09 release, and smol_str 0.1.17 is
incompatible with it.
I think there's still a puzzle piece missing, namely some form of CI that asserts deploy-rs keeps working with the nix releases that you wish to support (I am making the assumption that 20.09 is a reasonable target for now).
=> Debump the smol_str version to 0.1.16 to build on rust 1.45.2

Cargo.lock, Cargo.toml, flake.nix, src/activate.rs
I felt bad about the gross cargo workaround I left in the codebase for Darwin in #14, so I went in and ripped out the `inotify` dependency, in favor of a `notify` dependency - which is multiplatform and does a bunch of nice things for us (debounces events, automatically watches with less-sophisticated mechanisms if the watcher-of-the-day isn't working).
That required upgrading the tokio crate dep, but the upgrade was pretty painless.
The only thing I am not super happy with is the `eprintln` below; I don't think it's right to panic, as explained in the comment, but there's also no other way to tell the activation task that something is wrong.
What do you all think?
=> Build "activate" binary on all platforms

flake.nix
This should work around #31 in a backwards-compatible manner, it might be better to update that line rather than delete it (though the default without this line is the latest generation, which should be fine), but that would be more complex and we may not need it.
We should of course still fix this upstream in nixpkgs to eventually remove the need for this workaround
=> Remove default loader entry on NixOS activation

src/activate.rs
This stops problems from occuring when activation takes a long time to complete
=> Raise wait timeout

flake.nix
This will make `nix flake check` essentially run `cargo test`, and as it turns out it never attempts to build `defaultPackage` at all either, making our CI essentially useless, and this also fixes that.
=> Add Nix-flake check for checking build and Rust tests

src/deploy.rs
We previously started and abandoned the `ssh_activate` SSH session, which would let it spill into our shells, and mean that `wait` always has to time out (`deploy` will never error due to `activate` encountering an error). This PR will let the `activate` session end before the `wait` session, which occurs if an activation error is encountered, it then handles the error (if any) correctly.
fixes #58 and fixes #49 (I think)
=> Wait for activation

flake.nix
This should accomplish the same thing as https://github.com/serokell/deploy-rs/pull/39 but implemented slightly differently. Both are designed to work around NixOS/nixpkgs#73404, but this one sets the working directory inside the activation script, not the activation code.
The advantages of this method is we do not have the alter the functionality of deploy-rs, especially functionality we currently depend on (sadly) in many usages of deploy-rs. It is also fundamentally incorrect to make deploy-rs depend on the existence of `/tmp` in all contexts, and incorrect for deploy-rs internals to work around issues for specific deployment types, whereas instead this belongs in the deployment-type-specific logic in the `flake.nix` file (as has been changed here).
As correctly mentioned in discussion …
=> cd into `/tmp` during NixOS activation

src/bin/deploy.rs, src/deploy.rs, src/push.rs
I think the way command arguments were being added before was incorrect (and unnecessarily ugly), so I've gone and cleaned up all the obvious instances now.
=> Clean up adding Command arguments

examples/system/README.md
I assume that the intention is to use `deploy-rs` and not its predecessor, or have I misunderstood?
=> Fix examples/system/README.md: `deploy` -> `deploy-rs`

src/deploy.rs
This should fix #61, accomplishing the same thing as PR #62, though I also wanted to fix `ssh_addr` being uselessly reconstructed.
=> Remove `ssh://` prefix from SSH addresses

.buildkite/pipeline.yml
Without '-L' nix only prints logs on failure, and only the last 10
lines of them
=> CI: print full logs for `nix flake check`

flake.nix
This resolves #43, though I would also like to add example usage, and we may want to change out `hm` for `home-manager`, I'm not sure what one is best
=> Add helper activation function for home-manager

README.md
We now have a matrix channel. To increase community engagement, we should mention it in the README.
=> Mention the matrix channel in the README

flake.nix, src/push.rs
> Add rustfmt and rust-analyzer to devShell
I'm tired of adding this manually before I hack on this
> Evaluate only once, and then only realise
A dumb hack that uses `nix show-derivation` to get the deriver of a not-yet-existing path, and then builds that derivation using `nix build`/`nix-build`.
=> Evaluate only once, and then only realise

flake.lock, flake.nix
We weren't using any features of naersk that weren't covered by
buildRustPackage, so let's just use the tooling already in nixpkgs for Rust
builds and get rid of a flake input.
=> flake: replace naersk with buildRustPackage

README.md, src/cli.rs, src/data.rs, src/lib.rs
This is useful for nodes that utilize `doas` instead of `sudo`.
---
This is my first rust anything, so I'm not sure if any of this is correct (or if I can write unit tests).
I need to add documentation still as well, but getting it up in case my rust is bad was my first priority.
Closes #145
=> Add custom sudo command support

flake.nix
Nix 2.7 [renamed defaultApp and defaultPackage](https://discourse.nixos.org/t/nix-2-7-0-released/18072). Both the old and new names are supported in 2.7, but 2.8 has removed support for the old names, breaking the `nix run github:serokell/deploy-rs .` invocation.
Old names are kept in this PR to keep compatibility with nix 2.6, but could be removed if support of this version is not needed anymore.
PR tested with 2.6.1, 2.7.0 and 2.8.0
=> Update flake to support nix 2.8

flake.nix
The `runCommand` function has been using `stdenvNoCC` for quite a while and `runCommandNoCC` is correspondingly deprecated. See https://github.com/NixOS/nixpkgs/commit/9feb144c8cc4f4b71a9c23b2f7fd6b2ea55649e5.
=> Replace runCommandNoCC by runCommand

src/cli.rs
This PR introduces a non-zero code for rollbacks. This is particularly useful for CI/CD processes.
Closes #179
=> Introduce non-zero exit code for rollbacks

flake.nix
This PR introduces more unique names for the checks generated by the lib function to preserve unique names and therefore prevent possible name-clashing.
Closes #162
=> More unique names for the checks generated by deploy-rs

README.md, src/cli.rs, src/data.rs, src/lib.rs, src/push.rs
This PR adds the option to build the derivation on the target server instead of locally.
The derivation will first be uploaded to the target system and then built in the remote store.
Any required external dependencies will be fetched to the target host using the target system's substituters.
Fixes #12
=> Add option to build on the target host

flake.nix, src/bin/activate.rs, src/cli.rs, src/deploy.rs
This can be useful when e.g. deploying a kernel update to a target host. You usually plan a reboot (or kexec) after that to activate the new kernel. However you don't want to wait for services to be restarted first since these will be "restarted" anyways on the reboot. In cases like GitLab or the Atlassian stack this actually makes a difference.
This patch changes the following things:
* If `--boot` is provided, `nix-env -p profile-to-activate --set` is called for each deployed profile to make sure that it is activated automatically after a reboot.
* However, the actual activation (e.g. `switch-to-configuration switch`) is skipped. Instead:
* For NixOS, `switch-to-configuration boot` is called to set the new profile as default in the bootloader.
* For everything else, nothing else is …
=> Add new activation strategy `boot` as equivalent to `nixos-rebuild boot`

README.md, flake.nix
Use the deploy-rs from the final packages set. This can avoid rebuilding deploy-rs when using it in a nixos config. It can use the version cached in nixpkgs.
Also add instructions to the readme on how to craft an overlay that uses nixpkgs deploy-rs.
This should fix #163.
=> Make it possible to not rebuild deploy-rs

src/lib.rs
seems like `--confirm-timeout` doesn't do anything right now, as I was still getting the 30 second default even when sending in like, 120, or 9999. I believe this fixes it (though, difficult to test because my system is magically deploying quickly again... damn ghosts).
also the import at the top got rearranged because of rustfmt i guess.
=> actually merge confirm_timeout into merged_settings

flake.nix
`jsonschema-cli` is deprecated and will be removed in the future. The recommended replacement is `check-jsonschema`.
I tested the changes with my setup, the new cli gives a positive validation result on stdout.
=> Replace jsonschema-cli with check-jsonschema

.github/workflows/check.yml
Problem: We want to be able to run CI checks on PRs from external forks.
However, this is only possible with 'on: pull_request', while currently
CI is triggered 'on: push'
Solution: Change CI triggering condition to 'on: pull_request'.
=> [Chore] Run CI checks on 'pull_request'

interface.json, src/bin/activate.rs, src/cli.rs, src/data.rs, src/deploy.rs, src/lib.rs
Problem: Currently profile activation waiting timeout is hardcoded to 240 seconds, see https://github.com/serokell/deploy-rs/pull/48. In some cases, this timeout can be exceeded (e.g.
activation performs a heavy DB migration and waits for it to finish before considering the profile activation succesful).
Solution: Make this timeout configurable via 'activationTimeout' deploy attribute or corresponding '--activation-timeout' CLI option. For the sake of backward compatibility, the 'wait' subcommand new '--activation-timeout' option is made optional and defaults to 240 seconds if it wasn't provided.
=> [Chore] Make activation wait timeout configurable

src/bin/activate.rs
Problem: When profile activation confirmation fails due to
confirmation timeout and performs a rollback, zero exit code is
returned. Such a behavior is confusing since rollback usually means
something went wrong during deployment and it shouldn't return
successful exit code.
Solution: Explicitly return confirmation waiting error instead of
printing it and silently signaling success.
Resolves #245
=> [#245] Return non-zero exit code in case of confirmation timeout

README.md, src/cli.rs
Problem: README misses documentation for 'confirmTimeout' and 'activationTimeout'.
Solution: Mention them in README.
=> [Chore] Add missing documentation for timeout options

Cargo.lock, Cargo.toml, examples/system/flake.nix, interface.json, src/cli.rs, src/data.rs, src/deploy.rs, src/lib.rs
This adds a prompt for entering the sudo password interactively, so that system deployments can be activated when using non-root sshUsers. Fixes #78.
I have chosen to handle this locally (in deploy) and pipe the password to stdin of the ssh session, rather than via psuedo-terminal as this is more reliable. This also means that magicRollback works, unlike the "-t" workaround.
=> Add support for entering sudo password interactively

.github/workflows/check.yml, flake.nix, nix/tests/common.nix, nix/tests/default.nix, nix/tests/deploy-flake.nix, nix/tests/server.nix
Problem: Currently, the only way to test deploy-rs deployments is to actually do a deployment to an existing NixOS instance (either in VM, or a real machine) manually. This is a bit inconvenient and one can forget to test changes when developing/reviewing deploy-rs changes.
Solution: Add NixOS VM tests.
=> [OPS-1384] Introduce NixOS VM tests

README.md, flake.nix
Problem: In my recent PR(#264), I accidentally picked overlay output changes from the [philtaken/nixos-vm-tests](https://github.com/serokell/deploy-rs/tree/philtaken/nixos-vm-tests), which broke existing overlay imports after updating the deploy-rs input.
Solution: Add backwards compatibility so that users don't have to make changes to their nix flakes.
=> [Chore] Fix overlay

nix/tests/default.nix, src/cli.rs
for example
```sh
deploy .#s --hostname example.com --ssh-opts '-p 1145'
```
without `allow_hyphen_values`:
```
error: Found argument '-p' which wasn't expected, or isn't valid in this context
```
workaround: add a space after quote
```sh
deploy .#s --hostname example.com --ssh-opts ' -p 1145'
```
but it might be better adding `allow_hyphen_values = true`
=> allow --ssh-opts starts with hyphen

src/cli.rs
printing what node caused an error is very useful for debugging build or deployment failures, especially when deploying to several nodes at the same time
closes #273
=> better error messages: provide node names

flake.nix
Most importantly, this fixes `lib.getExe` and `pkgs.writeShellApplication` not working correctly.
=> add meta.mainProgram to rust drv

nix/tests/common.nix, nix/tests/default.nix, nix/tests/deploy-flake.nix, src/push.rs
The `drvpath^out` syntax is only part of `nix build`, not `nix-build`. The latter still behaves as before Nix 2.15 and produces the outPath, but produces an error if one attempts to call it the same way as `nix build`.
=> fix nix-build invocation in non-flake builds

README.md
Password-based sudo is implemented in #257 but not documented in the README.
See also: #78
=> doc: add option doc for interactiveSudo

nix/tests/default.nix, src/cli.rs, src/lib.rs, src/push.rs
This adds a `--file` option, which allows using `deploy` in repositories which are not nix flakes. `deploy-rs` already has support for falling back to a non-flake version of its logic in case the `nix` available in `$PATH` doesn't have the flake experimental feature flag enabled. However, that's an "if and only if"-situation: if the nix *is* flakes-enabled, there's no way to use the non-flake version. This works well for setups which use nix flakes, but provides a flake-compat `default.nix` fallback, but prevents use of `deploy-rs` in setups which do not use flakes at all but rely on another source-managing tool such as `niv` or `npins`.
`--file` takes as argument a path, and `--targets` and other options continue to work as expected; remote builds also work assuming a new enough nix on …
=> `--file` argument analogous to `nix build` & friends
